import { useEffect, useRef } from "react";

/** Inline Calendly scheduler. Zoom links are generated by the Calendly event itself. */
export function CalendlyEmbed({ url }: { url: string }) {
  const ref = useRef<HTMLDivElement | null>(null);

  useEffect(() => {
    if (!url) return;
    const id = "calendly-widget-script";
    if (!document.getElementById(id)) {
      const s = document.createElement("script");
      s.id = id;
      s.src = "https://assets.calendly.com/assets/external/widget.js";
      s.async = true;
      document.body.appendChild(s);
    }
  }, [url]);

  if (!url) return null;

  return (
    <div
      ref={ref}
      className="calendly-inline-widget w-full border border-border bg-background"
      data-url={`${url}${url.includes("?") ? "&" : "?"}hide_gdpr_banner=1`}
      style={{ minWidth: "280px", height: "760px" }}
    />
  );
}
